// =====================================================
// PROPOSED INTELLIGENCE QUEUE
// =====================================================
// Settings/Admin-only review surface. Lists DRAFT intelligence items
// for a basket + agent (typically the output of a manual research
// run) with per-item thesis-health classification and four operator
// actions: Promote to Memory, One-scan only, Archive, Reject.
//
// Hard rules:
//   - Items shown here are PROPOSED only. Promoting requires an
//     explicit operator click. The runner never auto-promotes.
//   - The queue cannot override engine verdicts, Credit View risk,
//     Trigger posture, stale-data warnings, capital fit, or
//     allowedActions.
//   - Trader-facing copy. No raw scoring tokens. No cron / queue
//     internals.
// =====================================================

import React, { useCallback, useMemo, useState } from "react";
import {
  listProposedIntelligence,
  classifyProposedItem,
} from "../../lib/portfolioCio/researchRunner.js";
import {
  promoteToAgentMemory,
  approveIntelligenceItem,
  archiveIntelligenceItem,
  deleteIntelligenceItem,
} from "../../lib/portfolioCio/agentMemoryStore.js";
import { SOURCE_LABELS } from "../../lib/portfolioCio/researchAutomationContract.js";

const PALETTE = {
  bg:        "#06090e",
  panelBg:   "#0d1117",
  cardBg:    "#0a0d12",
  border:    "#1e2530",
  borderSoft:"#21252a",
  text:      "#e2e8f0",
  textDim:   "#9ca3af",
  textFaint: "#6b7280",
  accentTeal:"#14b8a6",
  green:     "#22c55e",
  red:       "#ef4444",
  amber:     "#f59e0b",
  cyan:      "#06b6d4",
  purple:    "#a78bfa",
  slate:     "#64748b",
};

const KIND_TONES = {
  confirming:  PALETTE.green,
  challenging: PALETTE.red,
  mixed:       PALETTE.amber,
  neutral:     PALETTE.slate,
};

const KIND_LABELS = {
  confirming:  "Confirming",
  challenging: "Challenging",
  mixed:       "Mixed",
  neutral:     "Neutral",
};

const BASKETS = Object.freeze([
  { id: "ai_health_diagnostics", label: "AI Health / Diagnostics" },
  { id: "ai_infrastructure",     label: "AI Infrastructure" },
  { id: "robotics",              label: "Robotics" },
  { id: "saas_harvest",          label: "SaaS Harvest" },
  { id: "dividend_income",       label: "Dividend Income" },
  { id: "watchlist",             label: "Watchlist" },
]);

/**
 * @param {object} props
 * @param {string} [props.defaultBasketId]
 * @param {string} [props.defaultAgentId]
 * @param {number} [props.refreshTick]   bump to force a reload (used by AgentResearchSettings after a run)
 */
export default function ProposedIntelligenceQueue({
  defaultBasketId = "ai_health_diagnostics",
  defaultAgentId = "aiHealthDiagnosticsAgent",
  refreshTick = 0,
}) {
  const [basketId, setBasketId] = useState(defaultBasketId);
  const [tick, setTick] = useState(0);

  const items = useMemo(
    () => listProposedIntelligence({ basketId, agentId: defaultAgentId }),
    // eslint-disable-next-line react-hooks/exhaustive-deps
    [basketId, defaultAgentId, tick, refreshTick],
  );

  const handlePromote = useCallback((id) => {
    promoteToAgentMemory(id);
    setTick((n) => n + 1);
  }, []);
  const handleOneScan = useCallback((id) => {
    approveIntelligenceItem(id);
    setTick((n) => n + 1);
  }, []);
  const handleArchive = useCallback((id) => {
    archiveIntelligenceItem(id);
    setTick((n) => n + 1);
  }, []);
  const handleReject = useCallback((id) => {
    deleteIntelligenceItem(id);
    setTick((n) => n + 1);
  }, []);

  return (
    <section aria-label="Proposed intelligence queue"
      style={{
        background: PALETTE.bg,
        border: `1px solid ${PALETTE.border}`,
        borderRadius: 10, padding: 12,
        display: "flex", flexDirection: "column", gap: 10,
      }}>
      <header>
        <div style={{ fontSize: 9, letterSpacing: "0.14em", color: PALETTE.textDim, marginBottom: 4 }}>
          PROPOSED INTELLIGENCE QUEUE · {items.length}
        </div>
        <div style={{ fontSize: 11, color: PALETTE.text, lineHeight: 1.5 }}>
          Review draft intelligence generated by Research Automation. Approve to update the agent memory; archive or reject to drop. Engine verdicts and risk controls remain unchanged.
        </div>
      </header>

      <div style={{
        display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(220px, 1fr))", gap: 8,
      }}>
        <Field label="Basket">
          <select value={basketId} onChange={(e) => setBasketId(e.target.value)} style={inputStyle()}>
            {BASKETS.map((b) => (
              <option key={b.id} value={b.id}>{b.label}</option>
            ))}
          </select>
        </Field>
      </div>

      {items.length === 0 ? (
        <div style={emptyStyle()}>
          No proposed intelligence on the queue. Configure Research Automation above and click <strong style={{ color: PALETTE.text }}>Run research check</strong> to generate findings.
        </div>
      ) : (
        <ul style={{ margin: 0, padding: 0, listStyle: "none", display: "flex", flexDirection: "column", gap: 6 }}>
          {items.map((it) => (
            <ProposedItemCard key={it.id}
              item={it}
              basketId={basketId}
              onPromote={handlePromote}
              onOneScan={handleOneScan}
              onArchive={handleArchive}
              onReject={handleReject} />
          ))}
        </ul>
      )}
    </section>
  );
}

// ---------------------------------------------------------------------
// Card
// ---------------------------------------------------------------------

function ProposedItemCard({ item, basketId, onPromote, onOneScan, onArchive, onReject }) {
  const classification = useMemo(
    () => classifyProposedItem(item, { basketId }),
    [item, basketId],
  );
  const kindTone  = KIND_TONES[classification.kind] || PALETTE.slate;
  const kindLabel = KIND_LABELS[classification.kind] || "Neutral";
  const sourceLabel = SOURCE_LABELS[item.researchSource] || item.researchSource || null;
  const primary = (item.entities && item.entities.primarySymbols && item.entities.primarySymbols[0]) || null;

  return (
    <li style={{
      background: PALETTE.cardBg,
      border: `1px solid ${kindTone}55`,
      borderLeft: `3px solid ${kindTone}`,
      borderRadius: 8, padding: 10,
      display: "flex", flexDirection: "column", gap: 4,
    }}>
      <header style={{
        display: "flex", justifyContent: "space-between",
        alignItems: "baseline", gap: 6, flexWrap: "wrap",
      }}>
        <div style={{ display: "flex", alignItems: "baseline", gap: 6, flexWrap: "wrap" }}>
          {primary && (
            <span style={{
              fontSize: 12, fontWeight: 700, color: PALETTE.accentTeal, letterSpacing: "0.04em",
            }}>
              {primary}
            </span>
          )}
          <span style={{ fontSize: 11, color: PALETTE.text, fontWeight: 600 }}>
            {item.title || "Proposed intelligence item"}
          </span>
        </div>
        <div style={{ display: "flex", gap: 4, flexWrap: "wrap" }}>
          <Chip label={kindLabel} tone={kindTone} />
          {sourceLabel && <Chip label={`Source: ${sourceLabel}`} tone={PALETTE.cyan} />}
        </div>
      </header>

      {item.thesis && item.thesis.coreClaim && (
        <div style={{ fontSize: 11, color: PALETTE.textDim, lineHeight: 1.55 }}>
          {item.thesis.coreClaim}
        </div>
      )}

      {(Array.isArray(item.catalysts) && item.catalysts.length > 0) && (
        <SignalLine label="Catalysts" tone={PALETTE.green} items={item.catalysts} />
      )}
      {(Array.isArray(item.risks) && item.risks.length > 0) && (
        <SignalLine label="Risks" tone={PALETTE.red} items={item.risks} />
      )}

      <footer style={{
        display: "flex", gap: 4, flexWrap: "wrap",
        marginTop: 4, paddingTop: 6,
        borderTop: `1px solid ${PALETTE.borderSoft}`,
      }}>
        <button type="button" onClick={() => onPromote(item.id)} style={btn(PALETTE.green)}>
          Promote to Memory
        </button>
        <button type="button" onClick={() => onOneScan(item.id)} style={btn(PALETTE.cyan)}>
          One-scan only
        </button>
        <button type="button" onClick={() => onArchive(item.id)} style={btn(PALETTE.amber)}>
          Archive
        </button>
        <button type="button" onClick={() => onReject(item.id)} style={btn(PALETTE.red)}>
          Reject
        </button>
      </footer>
    </li>
  );
}

// ---------------------------------------------------------------------
// Sub-components
// ---------------------------------------------------------------------

function SignalLine({ label, tone, items }) {
  return (
    <div style={{ fontSize: 10, color: PALETTE.textDim, lineHeight: 1.5 }}>
      <strong style={{ color: tone, marginRight: 4 }}>{label}:</strong>
      {items.slice(0, 4).map((s, i) => (
        <span key={`${s}-${i}`} style={{ color: PALETTE.text }}>
          {i > 0 ? " · " : ""}{s}
        </span>
      ))}
      {items.length > 4 && (
        <span style={{ color: PALETTE.textFaint }}>
          {" · "}+{items.length - 4} more
        </span>
      )}
    </div>
  );
}

function Field({ label, children }) {
  return (
    <label style={{ display: "flex", flexDirection: "column", gap: 4 }}>
      <span style={{ fontSize: 9, letterSpacing: "0.10em", color: PALETTE.textFaint, fontWeight: 700 }}>
        {(label || "").toUpperCase()}
      </span>
      {children}
    </label>
  );
}

function Chip({ label, tone }) {
  return (
    <span style={{
      fontSize: 9, fontWeight: 700, letterSpacing: "0.06em",
      color: tone, background: `${tone}1a`,
      border: `1px solid ${tone}55`, borderRadius: 4, padding: "2px 6px",
    }}>
      {label}
    </span>
  );
}

function inputStyle() {
  return {
    background: PALETTE.panelBg, color: PALETTE.text,
    border: `1px solid ${PALETTE.border}`, borderRadius: 6,
    padding: "5px 8px", fontSize: 11, fontFamily: "inherit",
  };
}
function btn(color) {
  return {
    background: `${color}1a`, border: `1px solid ${color}88`, color,
    borderRadius: 5, padding: "4px 10px",
    fontSize: 10, fontWeight: 700, letterSpacing: "0.04em",
    cursor: "pointer", fontFamily: "inherit",
  };
}
function emptyStyle() {
  return {
    background: PALETTE.panelBg,
    border: `1px solid ${PALETTE.borderSoft}`,
    borderRadius: 8, padding: "12px 14px",
    fontSize: 11, color: PALETTE.textFaint, lineHeight: 1.55, fontStyle: "italic",
  };
}
